# Generated by Django 2.1.3 on 2019-09-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgprofile',
            old_name='org',
            new_name='user',
        ),
    ]
