# Generated by Django 2.1.3 on 2019-09-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190907_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='verification',
            field=models.BooleanField(default=True),
        ),
    ]
